### ISSUE TITLE
如果要用GLM4-voice的话能直接接入吗？还是需要额外的修改，不知道有没有用GLM4-voice的demo

### ISSUE THREAD

**Issue by Jimmy-L99** [opendilab/CleanS2S#10]
如题

**Comment by PaParaZz1** [comment]
需要额外的修改，得专门写一个 end-to-end 的 handler 来代替现在的 ASR+LLM+TTS 三部分，短期内我们的 roadmap 还是在优化 WebUI 和现有模型的推理速度，这方面的支持可能是需要外部贡献者了。
