### ISSUE TITLE
Any plan to multilanguage training/implementation

### ISSUE THREAD

**Issue by KadirErturk4r** [opendilab/CleanS2S#12]

**Comment by PaParaZz1** [comment]
For the current speech-to-speech (S2S) pipeline, the LLM typically supports both Chinese and English. If we aim to create an English S2S pipeline, it will be necessary to implement a new Speech-to-Text (STT) class (e.g., Whisper) and a Text-to-Speech (TTS) class (e.g., Parler TTS). Our immediate focus is on enhancing the web UI, improving inference speed, and supporting multiple users. Multi-language support is currently a lower priority. However, if anyone is interested in contributing to this feature, we are willing to provide assistance.
