### ISSUE TITLE
Implementation for Whisper and other models?

### ISSUE THREAD

**Issue by imPdhar** [opendilab/CleanS2S#13]
Hello, I come from [S2S repo's issue #32](https://github.com/huggingface/speech-to-speech/issues/132). So with regards to your implementation of an S2S with websockets for support on browser, I am interested to use whisper for STT, GPT API for the LLM and maybe mello, coqui or MMS for the TTS. I am aware that your implementation supports GPT API for LM but I was curious whether it supports the above mentioned STT and TTS models and if not, what is an approach I will have to take to implement it? 
Thanks in advance.

**Comment by PaParaZz1** [comment]
Thanks for your interest about our CleanS2S.

As mentioned in issue #12, implementing a new Speech-to-Text (STT) class (e.g., Whisper) and a Text-to-Speech (TTS) class (e.g., Parler TTS) is necessary to build an English speech-to-speech (S2S) pipeline. Specifically, this should involve replicating the current STT/TTS handler class and replacing the model initialization and inference code with those of the new models. We have currently placed this task in low priority. However, if you are interested in contributing to this feature, we are more than willing to provide assistance.

**Comment by imPdhar** [comment]
I see, so the current pipeline supports only chinese?

**Comment by PaParaZz1** [comment]
> I see, so the current pipeline supports only chinese?

The current STT and TTS models have not been sufficiently trained on English data, resulting in limited comprehension and a higher error rate when processing English.
