### ISSUE TITLE
英语版示意图中的小错误

### ISSUE THREAD

**Issue by byrTony-Frankzyq** [opendilab/CleanS2S#14]
https://github.com/opendilab/CleanS2S?tab=readme-ov-file#-real-time-streaming-interface

最下面the time elapsed between the end of the user's audio input and the _first_ sentence output by the agent: 7.1s

对照中文版本示意图应该是*second*

<img width="601" alt="截屏2024-11-05 22 02 35" src="https://github.com/user-attachments/assets/b11be26c-4fcc-4222-8693-78675dc8527a">

**Comment by PaParaZz1** [comment]
7.1s 就是 7.1second 的简称呀，应该没有歧义

**Comment by PaParaZz1** [comment]
> > 7.1s 就是 7.1second 的简称呀，应该没有歧义
> 
> 我意思是下面应该是the time elapsed between the end of the user's audio input and the **second** sentence output by the agent: 7.1s？

好的，这个问题已经在上面的 commit 中修复了，感谢反馈！
