### ISSUE TITLE
 got Future <Future pending> attached to a different loop: 

### ISSUE THREAD

**Issue by WJMismybestfriend** [opendilab/CleanS2S#15]
CosyVoice、STT、LLM、recv_handler、send_handler
都搞定了。但是服务中的SocketVADReceiver起来报错了
INFO:__main__:Receiver WebSocket server started at 0.0.0.0:9001
INFO:__main__:Sender WebSocket server started at 0.0.0.0:9002
INFO:__main__:Receiver WebSocket server closed
Exception in thread Thread-9:
Traceback (most recent call last):
....
    await fut
    RuntimeErrorawait fut
: RuntimeErrorTask <Task pending name='Task-1' coro=<SocketVADReceiver.run() running at s2s_server_pipeline.py:513> cb=[_run_until_complete_cb() at /home/.../anaconda3/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop: 
Task <Task pending name='Task-2' coro=<SocketSender.run() running at s2s_server_pipeline.py:665> cb=[_run_until_complete_cb() at /home/.../anaconda3/lib/python3.8/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop

**Comment by PaParaZz1** [comment]
你使用的 Python 版本是多少，或许你可以尝试换到 Python 3.10（如果你之前用的不是 3.10）
