### ISSUE TITLE
应该如何指定环境变量？NEXT_PUBLIC_FX_SEND_HOST 和 NEXT_PUBLIC_FX_RECV_HOST

### ISSUE THREAD

**Issue by WJMismybestfriend** [opendilab/CleanS2S#16]
后端9001和9002已经起来了，起前端时指定了两个环境变量。
export NEXT_PUBLIC_FX_SEND_HOST=10.24.107.xxx:9001
export NEXT_PUBLIC_FX_RECV_HOST=10.24.107.xxx:9002
但这样export似乎将后端HOST拼到了前端HOST后面，如ws://10.24.107.xxx:18086/10.24.107.xxx:9001。应该如何指定两个环境变量才正确呢？我理解应该直接请求10.24.107.xxx:9001和10.24.107.xxx:9002。
![image](https://github.com/user-attachments/assets/f590e6e0-4173-4dc2-97f9-841e4c6179df)

**Comment by PaParaZz1** [comment]
你这个现象确实很奇怪，虽然说推荐方案应该是写好一个`.env.local`文件，但你 export 环境变量应该也是 OK 的。

第一个点，你需要检查下，你设置环境变量的时候有没有加`ws://`前缀，必须是`export NEXT_PUBLIC_FX_SEND_HOST=ws://10.24.107.xxx:9001`才行。

第二个点，你可以加点打印（用console.log）看看具体使用环境的变量的代码段，检查下具体代码逻辑，链接在[这里](https://github.com/opendilab/CleanS2S/blob/main/frontend_nextjs/components/CardPanel.tsx#L35)

**Comment by WJMismybestfriend** [comment]
> 你这个现象确实很奇怪，虽然说推荐方案应该是写好一个`.env.local`文件，但你 export 环境变量应该也是 OK 的。
> 
> 第一个点，你需要检查下，你设置环境变量的时候有没有加`ws://`前缀，必须是`export NEXT_PUBLIC_FX_SEND_HOST=ws://10.24.107.xxx:9001`才行。
> 
> 第二个点，你可以加点打印（用console.log）看看具体使用环境的变量的代码段，检查下具体代码逻辑，链接在[这里](https://github.com/opendilab/CleanS2S/blob/main/frontend_nextjs/components/CardPanel.tsx#L35)

非常感谢，是没有加前缀的问题。ws://
