### ISSUE TITLE
如何替换TTS和STT成API服务？

### ISSUE THREAD

**Issue by jlia0** [opendilab/CleanS2S#17]
RT

**Comment by PaParaZz1** [comment]
这个 issue #13 类似，需要实现相应的 STT 和 TTS API 版本 Handler，近期我们无支持计划（主要这两块并没有像 LLM 形成稳定通用的 API 形式）

**Comment by jlia0** [comment]
> 这个 issue #13 类似，需要实现相应的 STT 和 TTS API 版本 Handler，近期我们无支持计划（主要这两块并没有像 LLM 形成稳定通用的 API 形式）

谢谢回复！我可以开个PR去添加这个功能，请问一下我主要需要修改哪些地方？STT可以用whisper， TTS可以用11labs。

**Comment by PaParaZz1** [comment]
好的，感谢你的贡献，我们也会尽量提供帮助。

具体来说，你需要新写两个类：
- STTAPIHandler，模仿 ParaFormerSTTHandler，实现用 API 调用的逻辑，并保持所有输入输出参数类型一致
- TTSAPIHandler，模仿 CosyVoiceTTSHandler，实现用 API 调用的逻辑，并保持所有输入输出参数类型一致

这两个类你可以基于`backend/tests`中的相应的测试文件来单独测试你实现的新类的效果，API_KEY的话建议用环境变量设置，类似 LLM 这边的[实现](https://github.com/opendilab/CleanS2S/blob/main/backend/s2s_server_pipeline.py#L1244)
