### ISSUE TITLE
服务端s2s_server_pipeline.py启动后无法通过ctrl+C关闭

### ISSUE THREAD

**Issue by 12915494174** [opendilab/CleanS2S#18]
服务端s2s_server_pipeline.py启动后无法通过ctrl+C关闭

**Comment by PaParaZz1** [comment]
确实是这样，你可以用这样的命令来关闭服务`kill -9 $(ps -ef | grep s2s | grep -v grep | awk 'NR==1 {print $2}')`

**Comment by 12915494174** [comment]
> 确实是这样，你可以用这样的命令来关闭服务`kill -9 $(ps -ef | grep s2s | grep -v grep | awk 'NR==1 {print $2}')`

好的
