### ISSUE TITLE
KeyError: 'timestamp'

### ISSUE THREAD

**Issue by Upcreat** [opendilab/CleanS2S#21]
麻烦问一下：
1、代码中的模型名称是不是需要进行更改，说明文档中的ASR为: [paraformer-zh]模型，代码中默认的不是。
2、在改成paraformer-zh模型以后出现新的问题。
  File "/ssd/LLM/human_ai/CleanS2S/backend/s2s_server_pipeline.py", line 764, in __init__
    self.warmup()
  File "/ssd/LLM/human_ai/CleanS2S/backend/s2s_server_pipeline.py", line 781, in warmup
    _ = self.model.generate(dummy_input, batch_size_s=300, batch_size_threshold_s=60)
  File "/home/ps/Soft/anaconda/yes/envs/cleans2s/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 304, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "/home/ps/Soft/anaconda/yes/envs/cleans2s/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 609, in inference_with_vad
    result["timestamp"],
![局部截取_20241206_152650](https://github.com/user-attachments/assets/9cffdfa4-ea9a-4e00-b33c-ad2fd022d2cc)
查询模型说明发现paraformer-zh模型是支持时间戳的，请问大概是什么地方出现了问题。
![局部截取_20241206_152951](https://github.com/user-attachments/assets/2a538b1a-8c04-4e0e-b793-e7e722efdcca)

**Comment by PaParaZz1** [comment]
1. 模型就是paraformer-zh，在代码中简写为ParaFormer而已
2. 你可以先尝试设置[这里](https://github.com/opendilab/CleanS2S/blob/main/backend/s2s_server_pipeline.py#L753)为 False，从而避开这个错误，目前 pipeline 中并没有使用这个时间戳功能。关于为什么会出现这个问题，猜测可能是 funasr 的版本问题。

**Comment by Upcreat** [comment]
谢谢您的回复，我换个funasr 的版本试试。

**Comment by whyiug** [comment]
> 1. 模型就是paraformer-zh，在代码中简写为ParaFormer而已
> 2. 你可以先尝试设置[这里](https://github.com/opendilab/CleanS2S/blob/main/backend/s2s_server_pipeline.py#L753)为 False，从而避开这个错误，目前 pipeline 中并没有使用这个时间戳功能。关于为什么会出现这个问题，猜测可能是 funasr 的版本问题。

我也碰到了同样的问题，按照这样修改(改为 False)之后，可以运行，但是无法识别语音。
还是换成了 seaco_paraformer（不改 False） ，可以正常运行和识别。
funasr version: 1.1.16
另外请教下，我的整个 pipeline （从提问到第一次回答）比较慢，我看你们的 demo 很快，如果想提升性能，可以从哪些方面考虑呢？

**Comment by PaParaZz1** [comment]
> 另外请教下，我的整个 pipeline （从提问到第一次回答）比较慢，我看你们的 demo 很快，如果想提升性能，可以从哪些方面考虑呢？

我们刚刚完成了 web ui 和 RAG 机制的升级，最近会着手来推进推理效率优化和多用户支持。

如果你要自己尝试优化的话，首先当然需要在你的运行环境里，对整个 pipeline 做一下运行时间统计（或 profile），分析时间瓶颈。整体上来看，TTS 部分应该是最有可能占大头的部分，简单一点你可以考虑替换为 cosyvoice 官方出的 CosyVoice-300M-25Hz 模型，会损失一点点效果，但是推理速度会提升一倍多。

**Comment by whyiug** [comment]
> 。

你的回复很有帮助，非常感谢！

**Comment by zajzhuaijun** [comment]
funasr version: 1.1.16. 还是会报错 result["timestamp"],KeyError: 'timestamp'，还有哪里的问题吗
