### ISSUE TITLE
服务端报错：prepare tts engine failed：AssertionError: failed to initialize ttsfrd resource

### ISSUE THREAD

**Issue by big-pan-whu** [opendilab/CleanS2S#22]
用python3.10，通过pip install ttsfrd -f https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html安装了installed ttsfrd-0.2.1，启动服务，报错：
![image](https://github.com/user-attachments/assets/afde077a-72e2-4b6e-9da0-39365f22a28b)

请问怎么解决？
PS：
用python3.8 安装pretrained_models/CosyVoice-ttsfrd目录里的ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl，是不会报这个错误，但会报：got Future <Future pending> attached to a different loop，查看issues，需用python3.10

**Comment by PaParaZz1** [comment]
不安装`ttsfrd`也行，CosyVoice中发现ttsfrd未安装的话会用另一个库，所以你可以试试在 python3.10的环境里 uninstall ttsfrd，然后运行看看。

**Comment by big-pan-whu** [comment]
> 不安装`ttsfrd`也行，CosyVoice中发现ttsfrd未安装的话会用另一个库，所以你可以试试在 python3.10的环境里 uninstall ttsfrd，然后运行看看。

卸载后ttsfrd后，后端服务起来了，谢谢解答！

另外，顺便请教一下，在python3.10下有安装ttsfrd的方案吗？

**Comment by PaParaZz1** [comment]
目前我们测试运行时都没有使用 ttsfrd，如果想深究这个问题，可以在 CosyVoice 官方仓库那边找找有没有相应的解决方案。

**Comment by big-pan-whu** [comment]
好的，谢谢，你的回复对我很有帮助
