### ISSUE TITLE
前端服务报错：favicon.ico:1     GET http://172.23.4.xxx:3001/favicon.ico 500 (Internal Server Error)

### ISSUE THREAD

**Issue by big-pan-whu** [opendilab/CleanS2S#23]
前端服务启动后，语音交互或文字交互无响应：
![CleanS2S](https://github.com/user-attachments/assets/028293fe-a368-4878-ab14-d3c54ac278f6)

F12查看报错信息提示favicon.ico路径冲突：A conflicting public file and page file was found for path /favicon.ico https://nextjs.org/docs/messages/conflicting-public-file-page

find命令查找到两个favicon.ico

![image](https://github.com/user-attachments/assets/6d322fad-ed15-4c3d-a00d-47446a4871ea)

补充：
.env.local文件内容：
![image](https://github.com/user-attachments/assets/8589e991-4cc7-48aa-a0d1-5c4eaaeac800)

请问该怎么解决？

**Comment by PaParaZz1** [comment]
favicon.ico报错这个问题应该不影响正常使用，应该是其他的问题导致交互无响应

**Comment by big-pan-whu** [comment]
是llm配置问题，以解决
