### ISSUE TITLE
KeyError: 'spk_embedding'

### ISSUE THREAD

**Issue by big-pan-whu** [opendilab/CleanS2S#24]
前后端服务都启起来了，在语音输入后，后端服务报错，报错信息如下：
![image](https://github.com/user-attachments/assets/d7f9cf9d-81d3-43c6-b6a6-ddf97f409ae2)

打印了spk_res参数，确实没有spk_embedding key，该错误怎么解决？

补充：python3.10，未安装ttsfrd，文字输入交互是OK的

**Comment by PaParaZz1** [comment]
你使用的funasr版本是多少，我们最新测试是使用funasr 1.1.6版本，且使用paraformer模型
