### ISSUE TITLE
got RuntimeError

### ISSUE THREAD

**Issue by Mahaotian1** [opendilab/CleanS2S#3]
could someone can help?
![图片](https://github.com/user-attachments/assets/5c42b34b-1866-4fe2-9dc2-6ee24561f9d4)

**Comment by PaParaZz1** [comment]
You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.

**Comment by Mahaotian1** [comment]
> You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.

thanks a lot， this ploblem， when i run the client and i got some error. How to run client?
![企业微信截图_17287217014248](https://github.com/user-attachments/assets/cfdba8dc-09ab-4ca2-bb72-3ba60015c174)
![企业微信截图_17287217118645](https://github.com/user-attachments/assets/9bfdcc2d-6f59-430e-8086-716fead67d51)
![企业微信截图_17287215394025](https://github.com/user-attachments/assets/491cf8a5-26f9-4e57-ae75-64736238c22e)

**Comment by Mahaotian1** [comment]
> You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.

点击交互没有反应，请问是什么问题呢？
![图片](https://github.com/user-attachments/assets/14ca4021-f7b6-48ce-a40a-e2138c2d4f8c)
![图片](https://github.com/user-attachments/assets/427d9ca9-71ea-4926-a1fe-aa80e8c9db85)

**Comment by PaParaZz1** [comment]
> > You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.
> 
> 点击交互没有反应，请问是什么问题呢？是env.local的问题吗？ ![图片](https://private-user-images.githubusercontent.com/91183565/375955030-14ca4021-f7b6-48ce-a40a-e2138c2d4f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwMzAtMTRjYTQwMjEtZjdiNi00OGNlLWE0MGEtZTIxMzhjMmQ0ZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTFlZjQ0MmRjZDNmNDg2ZDFiYTExYzZjZDg2NzYzY2NlMWY4NWM5OWQ1ZmQ3OTU3YTgzYmQ1NDFjMGE3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-5BwcrnjydWE9o53lFfAj9iGUecdf2rbQsQzdQpvvoM) ![图片](https://private-user-images.githubusercontent.com/91183565/375955060-427d9ca9-71ea-4926-a1fe-aa80e8c9db85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwNjAtNDI3ZDljYTktNzFlYS00OTI2LWExZmUtYWE4MGU4YzlkYjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjYxNWFiOTk3YWRjY2U3MWFjMjA1N2NiMjhlNDM1M2FmZWZiYTY0YzA5YjdhZDRmZWYzYzg2MTg3YTJhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GdTziIx9lwUh5VCHieW53k6FyXqmHMBIodqQAqcMiQQ)

那就是前端这边的问题了。有可能是因为你的浏览器麦克风使用权限没有打开。请问你使用的是什么浏览器？你可以根据浏览器类型去搜素一下怎么打开这个前端网页在浏览器中的麦克风使用权限。

**Comment by Mahaotian1** [comment]
> > > You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.
> > 
> > 
> > 点击交互没有反应，请问是什么问题呢？是env.local的问题吗？ ![图片](https://private-user-images.githubusercontent.com/91183565/375955030-14ca4021-f7b6-48ce-a40a-e2138c2d4f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwMzAtMTRjYTQwMjEtZjdiNi00OGNlLWE0MGEtZTIxMzhjMmQ0ZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTFlZjQ0MmRjZDNmNDg2ZDFiYTExYzZjZDg2NzYzY2NlMWY4NWM5OWQ1ZmQ3OTU3YTgzYmQ1NDFjMGE3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-5BwcrnjydWE9o53lFfAj9iGUecdf2rbQsQzdQpvvoM) ![图片](https://private-user-images.githubusercontent.com/91183565/375955060-427d9ca9-71ea-4926-a1fe-aa80e8c9db85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwNjAtNDI3ZDljYTktNzFlYS00OTI2LWExZmUtYWE4MGU4YzlkYjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjYxNWFiOTk3YWRjY2U3MWFjMjA1N2NiMjhlNDM1M2FmZWZiYTY0YzA5YjdhZDRmZWYzYzg2MTg3YTJhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GdTziIx9lwUh5VCHieW53k6FyXqmHMBIodqQAqcMiQQ)
> 
> 那就是前端这边的问题了。有可能是因为你的浏览器麦克风使用权限没有打开。请问你使用的是什么浏览器？你可以根据浏览器类型去 google 一下怎么打开这个前端网页在浏览器中的麦克风使用权限。

还是不行，用的谷歌浏览器，有访问麦克风权限，同意之后点击“开始交互”没有反应

**Comment by PaParaZz1** [comment]
那你可以这样排查：运行前端之后，在谷歌浏览器打开，按下 F12，查看控制台，看是否有报错信息。

是不是你没有配置前端的环境变量文件，即`.env.example`。需要在里面填入你自己启动的后端服务的相关URL才行。

**Comment by 12915494174** [comment]
> > > > You may consider utilizing Python 3.10 initially, as our development environment is configured with this specific setting. If you have further problems, you can continue to update in this issue.
> > > 
> > > 
> > > 点击交互没有反应，请问是什么问题呢？是env.local的问题吗？ ![图片](https://private-user-images.githubusercontent.com/91183565/375955030-14ca4021-f7b6-48ce-a40a-e2138c2d4f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwMzAtMTRjYTQwMjEtZjdiNi00OGNlLWE0MGEtZTIxMzhjMmQ0ZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTFlZjQ0MmRjZDNmNDg2ZDFiYTExYzZjZDg2NzYzY2NlMWY4NWM5OWQ1ZmQ3OTU3YTgzYmQ1NDFjMGE3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-5BwcrnjydWE9o53lFfAj9iGUecdf2rbQsQzdQpvvoM) ![图片](https://private-user-images.githubusercontent.com/91183565/375955060-427d9ca9-71ea-4926-a1fe-aa80e8c9db85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTI5NzYsIm5iZiI6MTcyODgxMjY3NiwicGF0aCI6Ii85MTE4MzU2NS8zNzU5NTUwNjAtNDI3ZDljYTktNzFlYS00OTI2LWExZmUtYWE4MGU4YzlkYjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA5NDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjYxNWFiOTk3YWRjY2U3MWFjMjA1N2NiMjhlNDM1M2FmZWZiYTY0YzA5YjdhZDRmZWYzYzg2MTg3YTJhZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GdTziIx9lwUh5VCHieW53k6FyXqmHMBIodqQAqcMiQQ)
> > 
> > 
> > 那就是前端这边的问题了。有可能是因为你的浏览器麦克风使用权限没有打开。请问你使用的是什么浏览器？你可以根据浏览器类型去 google 一下怎么打开这个前端网页在浏览器中的麦克风使用权限。
> 
> 还是不行，用的谷歌浏览器，有访问麦克风权限，同意之后点击“开始交互”没有反应

请问该问题，你解决了吗？目前我也到了这一步。。

**Comment by Mahaotian1** [comment]
> 那你可以这样排查：运行前端之后，在谷歌浏览器打开，按下 F12，查看控制台，看是否有报错信息。
> 
> 是不是你没有配置前端的环境变量文件，即`.env.example`。需要在里面填入你自己启动的后端服务的相关URL才行。

您看看我上几张图片，里面有个env.local的截图，您看看配置得对吗？

**Comment by PaParaZz1** [comment]
> > 那你可以这样排查：运行前端之后，在谷歌浏览器打开，按下 F12，查看控制台，看是否有报错信息。
> > 是不是你没有配置前端的环境变量文件，即`.env.example`。需要在里面填入你自己启动的后端服务的相关URL才行。
> 
> 您看看我上几张图片，里面有个env.local的截图，您看看配置得对吗？

不对，应该是`ws://<ip>:<port>`的格式

**Comment by Kylin2** [comment]
一样的问题，配置都配了，点击无反应，无报错
