### ISSUE TITLE
生成的录音是否有存储？

### ISSUE THREAD

**Issue by 12915494174** [opendilab/CleanS2S#7]
系统启动后，对话的录音和TTS生成的录音是否有存储到本地？

**Comment by PaParaZz1** [comment]
我们正在添加相应的功能，使得后端可以存储音频和对话记录。前端也会提供相应的接口，可以在 web 上下载音频。

**Comment by 12915494174** [comment]
> 我们正在添加相应的功能，使得后端可以存储音频和对话记录。前端也会提供相应的接口，可以在 web 上下载音频。

好的！辛苦！

**Comment by PaParaZz1** [comment]
目前前端和后端都添加了这个功能，可以参考上方的 commit
