### ISSUE TITLE
是否有计划支持声纹检测

### ISSUE THREAD

**Issue by YEY11** [opendilab/CleanS2S#8]
请问后续是否有计划支持主说话人的声纹检测功能呢，感觉这个对于嘈杂环境下的交互体验会有较大提升。

**Comment by PaParaZz1** [comment]
感谢你的建议，我们会把这个功能放到 roadmap 里，现在用的 paraformer 应该是有检测 speaker id 的能力的，但是在嘈杂环境下的能力我们还没有测试过。我们会在完成 Web UI 优化和推理加速之后，推进这个功能。

**Comment by YEY11** [comment]
> 感谢你的建议，我们会把这个功能放到 roadmap 里，现在用的 paraformer 应该是有检测 speaker id 的能力的，但是在嘈杂环境下的能力我们还没有测试过。我们会在完成 Web UI 优化和推理加速之后，推进这个功能。

好的，大佬辛苦，期待ing
