### ISSUE TITLE
i failed in the first step which is installation. I don't know how install the CosyVoice project with the CleanS2S project. Can help me? AnyOne?

### ISSUE THREAD

**Issue by daiDai-study** [opendilab/CleanS2S#9]

**Comment by PaParaZz1** [comment]
For the installation problem of CosyVoice, you can refer to its official [doc](https://github.com/FunAudioLLM/CosyVoice?tab=readme-ov-file#install). If you still have some problems about CosyVoice, you can raise an issue in the repository of CosyVoice.

**Comment by live-in-the-moment** [comment]
我目前状态也是，按照CosyVoice官网安装完成了，并搭建了环境。测试使用官方的例子代码也可以通过。但是在CleanS2S启动时却是找不到CosyVoice服务；

**Comment by 12915494174** [comment]
export PYTHONPATH=/root/autodl-tmp/CosyVoice:/root/autodl-tmp/CosyVoice/third_party/Matcha-TTS
需要使用这个命令指定一下。我的问题是这样解决的。

**Comment by daiDai-study** [comment]
> export PYTHONPATH=/root/autodl-tmp/CosyVoice:/root/autodl-tmp/CosyVoice/third_party/Matcha-TTS 需要使用这个命令指定一下。我的问题是这样解决的。

我试了这种，是OK的，现在有个问题，就是cosyvoice和cleans2s两个项目都有pytorch，但版本不同，我现在使用的pytorch2.4，然后安装的transformers是4.45.1，两者好像不太兼容，执行脚本python -u s2s_server_pipeline.py时报了段错误 (核心已转储)。请问你这边启动成功了，启动成功了话，pytorch 和 transformers的版本能方便透露一下吗？

**Comment by PaParaZz1** [comment]
> doc

是的需要加一下环境变量才能运行，cosyvoice 这个库并没有实现 pip 安装的部分，所以必须配一下 PYTHONPATH 才行

**Comment by PaParaZz1** [comment]
> > export PYTHONPATH=/root/autodl-tmp/CosyVoice:/root/autodl-tmp/CosyVoice/third_party/Matcha-TTS 需要使用这个命令指定一下。我的问题是这样解决的。
> 
> 我试了这种，是OK的，现在有个问题，就是cosyvoice和cleans2s两个项目都有pytorch，但版本不同，我现在使用的pytorch2.4，然后安装的transformers是4.45.1，两者好像不太兼容，执行脚本python -u s2s_server_pipeline.py时报了段错误 (核心已转储)。请问你这边启动成功了，启动成功了话，pytorch 和 transformers的版本能方便透露一下吗？

CleanS2S 本身对 pytorch 没什么特殊的兼容要求，建议你可以直接按着 cosyvoice 需要的来

**Comment by 12915494174** [comment]
> > export PYTHONPATH=/root/autodl-tmp/CosyVoice:/root/autodl-tmp/CosyVoice/third_party/Matcha-TTS 需要使用这个命令指定一下。我的问题是这样解决的。
> 
> 我试了这种，是OK的，现在有个问题，就是cosyvoice和cleans2s两个项目都有pytorch，但版本不同，我现在使用的pytorch2.4，然后安装的transformers是4.45.1，两者好像不太兼容，执行脚本python -u s2s_server_pipeline.py时报了段错误 (核心已转储)。请问你这边启动成功了，启动成功了话，pytorch 和 transformers的版本能方便透露一下吗？

我启动成功了。pytorch2.0.1+cu118    transformers4.46.0。

**Comment by daiDai-study** [comment]
> > > export PYTHONPATH=/root/autodl-tmp/CosyVoice:/root/autodl-tmp/CosyVoice/third_party/Matcha-TTS 需要使用这个命令指定一下。我的问题是这样解决的。
> > 
> > 
> > 我试了这种，是OK的，现在有个问题，就是cosyvoice和cleans2s两个项目都有pytorch，但版本不同，我现在使用的pytorch2.4，然后安装的transformers是4.45.1，两者好像不太兼容，执行脚本python -u s2s_server_pipeline.py时报了段错误 (核心已转储)。请问你这边启动成功了，启动成功了话，pytorch 和 transformers的版本能方便透露一下吗？
> 
> 我启动成功了。pytorch2.0.1+cu118 transformers4.46.0。

好的，谢谢，我试一试
